---
- name: Remove DNS record on local dns server
  community.general.nsupdate:
    server: "127.0.0.1"
    key_name: "local-ddns"
    key_algorithm: "hmac-sha256"
    key_secret:  "{{ sessionsecret_local }}"

    record: "{{ record }}"
    state: absent
  when:
    - rrtype == "A"  or rrtype == "both"
  delegate_to: "{{ nameserver }}"
  notify: Sync dns records into zone files

- name: Remove REVERS DNS record on local dns server
  community.general.nsupdate:
    server: "127.0.0.1"
    key_name: "local-ddns"
    key_algorithm: "hmac-sha256"
    key_secret:  "{{ sessionsecret_local }}"

    record: "{{ value | ansible.utils.ipaddr('revdns') }}"
    value: "{{ record }}."
    state: absent
  when:
    - rrtype == "PTR"  or rrtype == "both"
  delegate_to: "{{ nameserver }}"
  notify: Sync dns records into zone files
     

