---
- name: read session key from bastion host
  ansible.builtin.slurp:
    src: /var/run/named/session.key
  register: sessionkeyfile
  delegate_to: "{{ nameserver }}"

- name: convert sessionkyecontent to json format
  set_fact: 
    sessionkey_json: "{{ sessionkeyfile['content'] | b64decode
      | regex_replace ('^key\\s+','', multiline=true)
      | regex_replace ('algorithm','\"algorithm\":', multiline=true)
      | regex_replace ('secret','\"secret\":', multiline=true)
      | regex_replace ('hmac-(.+);','\"hmac-\\1\",', multiline=true)
      | regex_replace ('\\s+{',': {', multiline=true)
      | regex_replace (';',',', multiline=true)
      | regex_replace ('[\\r\\n\\t]+', '', multiline=true)
      | regex_replace ('^','{') | regex_replace ('$','}') 
      }}"

- name: debug sessionkeys
  debug:
    var: sessionkey_json
  when:
    - debug | default ('false') | bool

- name: extract file content in variable 
  set_fact: 
    sessionsecret_local: "{{ sessionkey_json['local-ddns'].secret }}"

- name: debug sessionsecret_local
  debug:
    var: sessionsecret_local
  when:
    - debug | default ('false') | bool
